apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: luna
  namespace: kube-system
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: luna-controller
  namespaceSelector:
    matchNames:
      - kube-system
  endpoints:
    - port: prometheus-metrics
      targetPort: 9090
      interval: 30s
      path: /metrics
