apiVersion: v1
kind: Namespace
metadata:
  name: demo-app
  labels:
    "sentinel.io/controlled": "enabled"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-1
  namespace: demo-app
  labels:
    app: demo-app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app-1
  template:
    metadata:
      labels:
        app: demo-app-1
    spec:
      containers:
      - name: nginx
        #image: nginx:1.28.2-alpine-slim 
        image: nginx:1.29.5-trixie
        #image: nginx:latest
        ports:
        - containerPort: 80
      - name: redis
        #image: redis:latest
        image: redis:8.4.0-bookworm
      - name: config-reloader-test
        image: quay.io/prometheus-operator/prometheus-config-reloader:v0.88.1


