apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test-app
  namespace: demo-app
  labels:
    app: nginx-test-app
  #  owner: matteo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-test-app
  template:
    metadata:
      labels:
        app: nginx-test-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /           
            port: 80           
          periodSeconds: 20      
          timeoutSeconds: 5       
          failureThreshold: 3   # After 3 consecutive failures, restart the container
        # readinessProbe:
        #   httpGet:
        #     path: /           
        #     port: 80          
        #   periodSeconds: 10      
        #   timeoutSeconds: 3   
        #   failureThreshold: 3    # After 3 consecutive failures, mark the container as NotReady
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test-app2
  namespace: demo-app2
  labels:
    app: nginx-test-app2
    owner: matteo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-test-app2
  template:
    metadata:
      labels:
        app: nginx-test-app2
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /           
            port: 80           
          periodSeconds: 20      
          timeoutSeconds: 5       
          failureThreshold: 3   # After 3 consecutive failures, restart the container
        readinessProbe:
          httpGet:
            path: /           
            port: 80          
          periodSeconds: 10      
          timeoutSeconds: 3   
          failureThreshold: 3    # After 3 consecutive failures, mark the container as NotReady

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crashloop-demo
  namespace: demo-app3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crashloop-demo
  template:
    metadata:
      labels:
        app: crashloop-demo
    spec:
      containers:
        - name: crash-container
          image: busybox
          command: ["sh", "-c", "sleep 10; echo 'Crash!'; exit 1"]

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-test-service
  namespace: demo-app
  labels:
    app: nginx-test-app
spec:
  selector:
    app: nginx-test-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-test-app2-service
  namespace: demo-app2
  labels:
    app: nginx-test-app2
spec:
  selector:
    app: nginx-test-app2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
